### ISSUE TITLE
[mesheryctl] improve `mesheryctl registry update`

### ISSUE THREAD

**Issue by devhindo** [meshery/meshery#13016]
so running this 
```console
$ mesheryctl registry update
Error: unexpected end of JSON input
```
this not a desired behavior, instead it should print out the help of this command as it seems that it's a false command that's missing args

**Comment by TusharMohapatra07** [comment]
@devhindo I'd like to work on this issue

**Comment by TusharMohapatra07** [comment]
I'm really sorry for the overlook, by mistake i pushed some code from my previous contribution too

**Comment by pratikgitss** [comment]
I think the PR by @TusharMohapatra07 doesn't fix the issue, the Error provided above is still shown and i think we should not replace the err as you done with cmd.Help().

**Comment by devhindo** [comment]
this is really valid solution! you should check this out @TusharMohapatra07

**Comment by TusharMohapatra07** [comment]
@devhindo Yes, i'll go through it once again. Thanks for the help @pratikgitss :)
