### ISSUE TITLE
[mesheryctl] Invalid Meshery endpoint returned on Kubernetes platform (Docker Desktop)

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2910]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
`system start` identifies Meshery endpoint on wrong port. IN this case, it identifies `9081` when it is `32389` that the Meshery service is exposed on.

#### Screenshots/Logs
```
mesheryctl version
        VERSION         GITSHA      
Client  v0.5.12         7d76b2db   
Server  unavailable     unavailable

  Unable to communicate with Meshery: Get http://localhost:9081/api/server/version: dial tcp [::1]:9081: connect: connection refused
  See https://docs.meshery.io for help getting started with Meshery.

Checking for latest version of Meshery...

  v0.5.12 is the latest Meshery release.

➜  ~ mesheryctl system context create k8s -p kubernetes
Added `k8s` context

➜  ~ mesheryctl system context switch k8s              
switched to context 'k8s'

➜  ~ mesheryctl system start
creating ~/.meshery/manifests folder...
downloading manifest files from https://github.com/layer5io/meshery/tree/v0.5.12/install/deployment_yamls/k8s
Starting Meshery...
...Meshery deployed on Kubernetes.
Opening Meshery in your browser. If Meshery does not open, please point your browser to http://localhost:9081 to access Meshery.

➜  ~ mesheryctl system status
NAME                    READY   UP-TO-DATE      AVAILABLE       AGE 
meshery                 1/1     1               1               41s
meshery-consul          1/1     1               1               35s
meshery-cpx             1/1     1               1               31s
meshery-istio           1/1     1               1               38s
meshery-kuma            1/1     1               1               32s
meshery-linkerd         1/1     1               1               37s
meshery-nsm             1/1     1               1               34s
meshery-operator        1/1     1               1               17s
meshery-osm             1/1     1               1               29s
meshery-traefik-mesh    1/1     1               1               28s
Meshery endpoint is http://localhost:9081

➜  ~ kg svc -A    
NAMESPACE     NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
meshery       meshery                            NodePort    10.107.111.161   <none>        9081:32389/TCP           63s
meshery       meshery-consul                     ClusterIP   10.110.146.191   <none>        10002/TCP                57s
meshery       meshery-cpx                        ClusterIP   10.96.47.113     <none>        10008/TCP                52s
meshery       meshery-istio                      ClusterIP   10.110.221.54    <none>        10000/TCP                60s
meshery       meshery-kuma                       ClusterIP   10.109.195.176   <none>        10007/TCP                53s
meshery       meshery-linkerd                    ClusterIP   10.101.191.107   <none>        10001/TCP                58s
meshery       meshery-nsm                        ClusterIP   10.111.44.54     <none>        10004/TCP                55s
meshery       meshery-operator-metrics-service   ClusterIP   10.108.119.88    <none>        8443/TCP                 40s
meshery       meshery-osm                        ClusterIP   10.109.63.127    <none>        10009/TCP                50s
meshery       meshery-traefik-mesh               ClusterIP   10.105.185.184   <none>        10006/TCP                49s
```

- Host OS: MacOS
- Meshery Version: v0.5.12
- Platform: Kubernetes (Docker Desktop)

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)

**Comment by leecalcote** [comment]
@meshery/mesheryctl-contributors

**Comment by navendu-pottekkat** [comment]
@leecalcote @metonymic-smokey I'm getting the same error when I try on minikube and kind.

In both, I do not have an external load balancer but the endpoint which meshery detects is localhost. I guess this should be fixed if I have a loadbalancer but I'm not sure.

If I deploy to minikube should I get the endpoint as `<minikube ip>:port` ?

Anyway, this would not be an error in mesheryctl particularly as we use the function from meshkit. @abhishekkumkar

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat I'm facing the same issue when i try with `upstream/master` :( 
This definitely wasn't the case earlier when the `system status` PR was merged. It was navigating to the right endpoints correctly.

**Comment by kumarabd** [comment]
This is fixed I believe. @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
@kumarabd It is still an issue. The endpoints are still wrong when deploying to Kubernetes.
