### ISSUE TITLE
[UI] Yaml editor overflows off the screen.

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery#5862]
#### Current Behavior
The yaml editor overflows off the screen. 
<img width="1680" alt="Screenshot 2022-07-21 at 7 24 19 PM" src="https://user-images.githubusercontent.com/53532328/180231699-9babd578-aa75-4b9e-bb64-aded1d1d984d.png">

#### Desired Behavior
The editor should have a horizontal scroll instead.

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Gents, heads-up - https://github.com/meshery/meshery/pull/5846

**Comment by Zain-Muiz** [comment]
> Gents, heads-up - #5846

Uh oh, The mentioned fix was for overlapping text . Since the design was also changed, this error(overflow) could possibly have been fixed this too.. Ill look out when that PR is merged.

**Comment by Chadha93** [comment]
@Zain-Muiz Did you test @subhradwip01 's PR? I checked out, this is still an issue. Login via none provider and test a few designs to replicate the issue. 
@subhradwip01 Since you have made a similar fix here https://github.com/meshery/meshery/pull/5846 will you also ensure this one is also fixed?

Tag team @Zain-Muiz and @subhradwip01 if required. :)

**Comment by subhradwip01** [comment]
> @Zain-Muiz Did you test @subhradwip01 's PR? I checked out, this is still an issue. Login via none provider and test a few designs to replicate the issue. @subhradwip01 Since you have made a similar fix here #5846 will you also ensure this one is also fixed?
> 
> Tag team @Zain-Muiz and @subhradwip01 if required. :)

In my issue i just solved the text overlapping problem.. but tgis overflow issue is occurring in my case also... if you want I can look into that

**Comment by Chadha93** [comment]
> > @Zain-Muiz Did you test @subhradwip01 's PR? I checked out, this is still an issue. Login via none provider and test a few designs to replicate the issue. @subhradwip01 Since you have made a similar fix here #5846 will you also ensure this one is also fixed?
> > Tag team @Zain-Muiz and @subhradwip01 if required. :)
> 
> In my issue i just solved the text overlapping problem.. but tgis overflow issue is occurring in my case also... if you want I can look into that

Thank you

**Comment by subhradwip01** [comment]
@Chadha93 sorry fo the delay... I was actually working the restructuring branch... I saw that this problem is because of Codemirror... codemirror is unable to wrap the lines... I also saw thus type of problem in their repo... let me see if any other way is possible...

**Comment by Chadha93** [comment]
> @Chadha93 sorry fo the delay... I was actually working the restructuring branch... I saw that this problem is because of Codemirror... codemirror is unable to wrap the lines... I also saw thus type of problem in their repo... let me see if any other way is possible...

Thanks, @subhradwip01. Let me also we what we can do here.

**Comment by subhradwip01** [comment]
> > @Chadha93 sorry fo the delay... I was actually working the restructuring branch... I saw that this problem is because of Codemirror... codemirror is unable to wrap the lines... I also saw thus type of problem in their repo... let me see if any other way is possible...
> 
> Thanks, @subhradwip01. Let me also we what we can do here.

May be we can use other code editor...

**Comment by Chadha93** [comment]
> > > @Chadha93 sorry fo the delay... I was actually working the restructuring branch... I saw that this problem is because of Codemirror... codemirror is unable to wrap the lines... I also saw thus type of problem in their repo... let me see if any other way is possible...
> > 
> > 
> > Thanks, @subhradwip01. Let me also we what we can do here.
> 
> May be we can use other code editor...

A new code editor won't be feasible at the moment. 
We can control this formatting in the backend, see this slack conversation:  https://meshery.slack.com/archives/C012UMS2MCM/p1661289401727409

**Comment by subhradwip01** [comment]
> > > > @Chadha93 sorry fo the delay... I was actually working the restructuring branch... I saw that this problem is because of Codemirror... codemirror is unable to wrap the lines... I also saw thus type of problem in their repo... let me see if any other way is possible...
> > > 
> > > 
> > > Thanks, @subhradwip01. Let me also we what we can do here.
> > 
> > 
> > May be we can use other code editor...
> 
> A new code editor won't be feasible at the moment. We can control this formatting in the backend, see this slack conversation: https://meshery.slack.com/archives/C012UMS2MCM/p1661289401727409

Ok👍
