### ISSUE TITLE
[Bug Fix] Fix SVG scaling Problem in Folder: MesheryPerformance

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#7035]
Fix the problems with SVG in MesheryMeshInterface
Folder: https://github.com/meshery/meshery/tree/master/ui/components/MesheryPerformance

All the files here should be incorporating the changes, described below.

---

When an icon is used directly from the libraries like MUI or font-awesome or something else, always specify the height and width prop.

---

There are some set of SVG styles [specifying common height and width](https://github.com/meshery/meshery/pull/6690/files#diff-06f61349be806f176b8c47957b6dc8f701835c0ba8ef8313106488a361833aa8)

All the icons imported from any library, could be either small, or medium, or large, or xl. One of these styles based on icon demand should be applied to all those svgs.

Examples of how to do it: 
- https://github.com/meshery/meshery/pull/6690/commits/ecc260461b6015ca680d6969e01bfa9565f373f2
- https://github.com/meshery/meshery/pull/6690/commits/4b000e07a2eeb70c402085cdf86544783bcc939c

Files Done:

1. ui/components/CatalogFilter.js
2. ui/components/ConfirmationModal.js
3. ui/components/Content.js
4. ui/components/CustomTableFooter.js
5. ui/components/DashboardComponent.js
6. ui/components/ErrorHandling.js
7. ui/components/Filters.js
8. ui/components/Header.js
9. ui/components/MeshAdapterConfigComponent.js
10. ui/components/MesherySettings.js
11. ui/components/MeshConfigComponent.js
12. ui/components/MesheryAdapterPlayComponent.js
13. ui/components/MesheryApplications.js
14. ui/components/MesheryMetrics.js
15. ui/components/MesheryNotification.js

_Originally posted by @Abhishek-kumar09 in https://github.com/meshery/meshery/issues/6690#issuecomment-1384202999_

**Comment by yash37158** [comment]
hey @Abhishek-kumar09  I would like to work on this issue

**Comment by yash37158** [comment]
Which all svg needs to be fixed in Mesh Performance?

**Comment by Abhishek-kumar09** [comment]
Any SVG that is imported from MUI or font-awesome library. You can look into closed PRs for references.

**Comment by yash37158** [comment]
Here as you can see that the facebook svg looks weird. how should i approach this ?
<img width="700" alt="Screenshot 2023-02-15 at 2 07 10 AM" src="https://user-images.githubusercontent.com/68152307/218856983-f9889d36-1c1f-4496-8886-6af544f11662.png">

**Comment by leecalcote** [comment]
@yash37158 Here you are - https://docs.meshery.io/project/contributing/contributing-ui#static-files-icons-and-images

**Comment by yash37158** [comment]
okay so I have fixed the icon they were wrongly styled
<img width="700" alt="Screenshot 2023-02-15 at 10 35 03 AM" src="https://user-images.githubusercontent.com/68152307/218936950-3a09c4b7-c8b8-4ac1-bc76-fd9f66ed544f.png">

**Comment by ashutosh887** [comment]
@leecalcote @Abhishek-kumar09 I would like to work on this if not resolved

**Comment by Abhishek-kumar09** [comment]
@yash37158 What was the update here? Did we came to merge this?

**Comment by Gauravjadhav22** [comment]
hey @Abhishek-kumar09 ,
I want to work on this issue, is anyone already working on this or it has resolved?

**Comment by thisiskaransgit** [comment]
Closed as completed via #7137
