### ISSUE TITLE
[Docs] Search: Unwanted display of search result on separate line from bullet point

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7402]
@VIKAS0264, thanks for this.

On a related note, we seem to have another bug present here: an unwanted line return:

<img width="354" alt="Screenshot 2023-03-26 at 9 52 50 PM" src="https://user-images.githubusercontent.com/7570704/227829283-ef55e03a-029e-48ee-9075-62d89a0f9adc.png">

I see this behavior in Safari.

_Originally posted by @leecalcote in https://github.com/meshery/meshery/issues/7347#issuecomment-1484405105_

**Comment by leecalcote** [comment]
@VIKAS0264 is this an item that you can work on? Do you have access to Safari?

**Comment by VIKAS0264** [comment]
> @VIKAS0264 is this an item that you can work on? Do you have access to Safari?

Hey lee I've an idea of what's happening there i will work on this issue

**Comment by leecalcote** [comment]
Thanks much, @VIKAS0264 👍

**Comment by vishalvivekm** [comment]
> > @VIKAS0264 is this an item that you can work on? Do you have access to Safari?
> 
> Hey lee I've an idea of what's happening there i will work on this issue



> > @VIKAS0264 is this an item that you can work on? Do you have access to Safari?
> 
> Hey lee I've an idea of what's happening there i will work on this issue

@VIKAS0264 would you like to give us an update about your progress on this issue

**Comment by VIKAS0264** [comment]
> > > @VIKAS0264 is this an item that you can work on? Do you have access to Safari?
> > 
> > Hey lee I've an idea of what's happening there i will work on this issue
> 
> 
> 
> > > @VIKAS0264 is this an item that you can work on? Do you have access to Safari?
> > 
> > Hey lee I've an idea of what's happening there i will work on this issue
> 
> @VIKAS0264 would you like to give us an update about your progress on this issue

Hey guys sorry, I was busy with my personal work. If anyone is interested in this issue please work on it.

**Comment by ankur0904** [comment]
Hi @leecalcote @vishalvivekm I want to work on this issue. But I don't have access to Safari.
Can I still work on this issue?

**Comment by infernocodes** [comment]
is this issue is resolved now??

**Comment by vishalvivekm** [comment]
> is this issue is resolved now??

This issue still persists.
would you like take up and fix it @infernocodes ?

**Comment by leecalcote** [comment]
@infernocodes assigned.

**Comment by vishalvivekm** [comment]
update @infernocodes ?

**Comment by Jaishree2310** [comment]
I would like to take this issue can someone please assign it to me?

**Comment by Ghat0tkach** [comment]
@Jaishree2310 pardon I missed to ask , this is safari specific issue . Do you have access to safari?

**Comment by Jaishree2310** [comment]
@Ghat0tkach  yes i have.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach  yes i have.
> 
> 

Oh well , All the best🙌
